#ifndef BT3D_CONSTANTS_H
#define BT3D_CONSTANTS_H

#define DEFAULT_SCREEN_WIDTH 1280
#define DEFAULT_SCREEN_HEIGHT 720
#define BT3D_TARGET_FPS 144
#define WALL_HEIGHT 1.0f
#define PLAYER_HEIGHT 0.55f
#define PLAYER_RADIUS 0.18f
#define MOVE_SPEED 3.2f
#define TURN_SPEED 0.0028f
#define MOUSE_SENSITIVITY_MIN 0.2f
#define MOUSE_SENSITIVITY_MAX 3.0f
#define EVENT_SPEED_NORMAL (24.0f / 64.0f)
#define EVENT_SPEED_FAST (48.0f / 64.0f)
#define PLAYER_USE_DISTANCE 1.3f
#define PICKUP_DISTANCE 0.65f
#define ENEMY_MOVE_SPEED 1.8f
#define ENEMY_RADIUS 0.22f
#define MARKER_BILLBOARD_SIZE 1.0f
#define ENEMY_BILLBOARD_SIZE 1.0f
#define OVERLAY_ANIMATION_STEP 0.066f
#define BT3D_OVERLAY_ANIMATION_COUNT 16
#define GAME_TICK_SECS 0.066f
#define PLAYER_PROJECTILE_SPEED ((60.0f / 64.0f) / GAME_TICK_SECS)
#define PLAYER_PROJECTILE_BLAST_RADIUS (95.0f / 64.0f)
#define MAX_PLAYER_PROJECTILES 32
#define MAX_ENEMY_PROJECTILES 64
#define MAX_PLAYER_SHOT_IMPACTS 16
#define VISIBILITY_MASK_RAY_COUNT 1024
#define MAX_RAY_STEPS 96
#define SAVE_MAGIC 0x42543344u
#define SAVE_FORMAT_VERSION 3u
#define MAX_SAVE_ENTRIES 16

#define MENU_SCREEN_MAIN 0
#define MENU_SCREEN_LOAD 1
#define MENU_SCREEN_SAVE_DIALOG 2
#define MENU_SCREEN_OPTIONS 3
#define MENU_SCREEN_DIFFICULTY 4
#define MENU_SCREEN_CAMPAIGN 5

#define BT3D_DISPLAY_BORDERLESS 0
#define BT3D_DISPLAY_WINDOWED 1

#define BT3D_DIFFICULTY_EASY   0
#define BT3D_DIFFICULTY_MEDIUM 1
#define BT3D_DIFFICULTY_HARD   2

#define ENEMY_ANIM_WALK 0
#define ENEMY_ANIM_SHOOT 1
#define ENEMY_ANIM_PAIN 2
#define ENEMY_ANIM_DIE 3

#endif
