function(bt3d_configure_desktop_target target_name)
    if (APPLE)
        target_link_libraries(${target_name} PRIVATE "-framework IOKit" "-framework Cocoa" "-framework OpenGL")
    elseif (WIN32)
        target_link_libraries(${target_name} PRIVATE opengl32 gdi32 winmm)
        if (MINGW)
            target_link_options(${target_name} PRIVATE -mwindows)
        endif()
    endif()
endfunction()
