function(bt3d_link_desktop_or_web_raylib target_name)
    if (BT3D_FETCH_RAYLIB OR BT3D_PLATFORM_WEB)
        include(FetchContent)
        FetchContent_Declare(
            raylib
            GIT_REPOSITORY https://github.com/raysan5/raylib.git
            GIT_TAG 5.5
            GIT_SHALLOW TRUE
        )
        if (BT3D_PLATFORM_WEB)
            set(PLATFORM Web CACHE STRING "raylib platform" FORCE)
            set(GRAPHICS GRAPHICS_API_OPENGL_ES2 CACHE STRING "raylib graphics API" FORCE)
        endif()
        set(BUILD_EXAMPLES OFF CACHE BOOL "Build raylib examples" FORCE)
        set(BUILD_GAMES OFF CACHE BOOL "Build raylib games" FORCE)
        set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build raylib as a shared library" FORCE)
        FetchContent_MakeAvailable(raylib)
        target_link_libraries(${target_name} PRIVATE raylib)
    elseif (BT3D_RAYLIB_ROOT)
        target_include_directories(${target_name} PRIVATE "${BT3D_RAYLIB_ROOT}/include")
        if (BT3D_STATIC_RAYLIB)
            bt3d_link_static_raylib(${target_name} "${BT3D_RAYLIB_ROOT}/lib")
        else()
            find_library(BT3D_RAYLIB_DYLIB NAMES raylib HINTS "${BT3D_RAYLIB_ROOT}/lib" NO_DEFAULT_PATH)
            if (NOT BT3D_RAYLIB_DYLIB)
                message(FATAL_ERROR "raylib library not found in ${BT3D_RAYLIB_ROOT}/lib")
            endif()
            target_link_libraries(${target_name} PRIVATE ${BT3D_RAYLIB_DYLIB})
        endif()
    else()
        find_package(raylib REQUIRED)
        if (BT3D_STATIC_RAYLIB)
            get_target_property(_BT3D_RAYLIB_DYLIB raylib LOCATION)
            get_filename_component(_BT3D_RAYLIB_DIR "${_BT3D_RAYLIB_DYLIB}" DIRECTORY)
            get_target_property(_BT3D_RAYLIB_INCS raylib INTERFACE_INCLUDE_DIRECTORIES)
            if (_BT3D_RAYLIB_INCS)
                target_include_directories(${target_name} PRIVATE ${_BT3D_RAYLIB_INCS})
            endif()
            bt3d_link_static_raylib(${target_name} "${_BT3D_RAYLIB_DIR}")
        else()
            target_link_libraries(${target_name} PRIVATE raylib)
        endif()
    endif()
endfunction()

# Links libraylib.a from `search_dir`; configure fails if it is not there.
function(bt3d_link_static_raylib target_name search_dir)
    find_file(BT3D_RAYLIB_STATIC NAMES libraylib.a HINTS "${search_dir}" NO_DEFAULT_PATH)
    if (NOT BT3D_RAYLIB_STATIC)
        message(FATAL_ERROR "BT3D_STATIC_RAYLIB=ON but libraylib.a not found in ${search_dir}")
    endif()
    message(STATUS "Static raylib: ${BT3D_RAYLIB_STATIC}")
    target_link_libraries(${target_name} PRIVATE ${BT3D_RAYLIB_STATIC})
endfunction()
